// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAic326IsMz7jJTxBYBGyDBYRA4eMUz9U',
    appId: '1:110646298161:web:b9316e6927c75cf2af7710',
    messagingSenderId: '110646298161',
    projectId: 'aulansah-tv',
    authDomain: 'aulansah-tv.firebaseapp.com',
    storageBucket: 'aulansah-tv.appspot.com',
    measurementId: 'G-5EF9MPJWFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl6AglWKYNgljHPH5BvTU8oMP0kkzhwUg',
    appId: '1:110646298161:android:a2a0dc54edf6da11af7710',
    messagingSenderId: '110646298161',
    projectId: 'aulansah-tv',
    storageBucket: 'aulansah-tv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo0k2XGGnglXTenX2CpPQrJPCO4uYLGf0',
    appId: '1:110646298161:ios:110219360dcc08c9af7710',
    messagingSenderId: '110646298161',
    projectId: 'aulansah-tv',
    storageBucket: 'aulansah-tv.appspot.com',
    iosClientId: '110646298161-0vakijjfnt0v33up16ipsiq1f5065h5l.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
