name: movies
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core

  sqflite: ^2.0.0+3
  http: ^0.13.3
  equatable: ^2.0.3
  dartz: ^0.10.0
  flutter_bloc: ^8.1.1
  cached_network_image: ^3.1.0
  bloc: ^8.1.0
  flutter_rating_bar: ^4.0.0
  rxdart: ^0.27.1
  lottie: ^2.0.0
  firebase_core: ^2.3.0
  firebase_crashlytics: ^3.0.6

dev_dependencies:
  mockito: ^5.0.8
  build_runner: ^2.0.4
  bloc_test: ^9.0.0
  mocktail: ^0.3.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter: